name: My First Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest       
        steps:
        - name: checkout repo
          uses: actions/checkout@v6

        - name: list and read fie
          run: |
            echo "my first github action job"
            ls -lart
            cat README.md
        - name: generate ASCIIDOC file
          run: cowsay -f dragon "ASCIIDOC file generated" > dragon.txt
          


       