name: generate ascii artwork

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest       
        steps:
        #- name: checkout repo
        #  uses: actions/checkout@v6

        - name: check repo file
          run: ls -lart 
            
        - name: executing shell command
          run: |
            chmod +x ascii-script.sh 
            ./ascii-script.sh

          
        
          


       