name: variable secret test
on: push
env:
  CONTAINER_REGISTRY: docker.io
  IMAGE_NAME: github-actions-nginx  
    
jobs:
    docker:
        runs-on: ubuntu-latest       
        steps:
        - name: docker build
          run: echo docker build -t  ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest .
         

        - name: docker login          
          run: echo docker login --username ${{ vars.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }} ${{ env.CONTAINER_REGISTRY }}
          
        - name: list images
          run: docker image ls
            
        - name: docker publish
          run: echo docker push ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          
    deploy:
        needs: docker
        runs-on: ubuntu-latest       
        steps:
        - name: deploy run            
          run: echo docker run -d -p 8080:80 ${{ env.CONTAINER_REGISTRY }}/${{ vars.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:latest     

        - name: list images
          run: docker image ls
